name: Trigger

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  handle-event:
    runs-on: ubuntu-latest

    steps:
      - name: Print the trigger type
        run: echo 'Triggered by: ${{ github.event_name }}'

