name: Trigger

on:
  push:                        
  workflow_dispatch:          
  schedule:                   
    - cron: "*/2 * * * *"     

jobs:
  handle-event:
    runs-on: ubuntu-latest

    steps:
      - name: Print the trigger type
        run: echo "Triggered by: ${{ github.event_name }}"

      - name: Check trigger and respond
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "Code was pushed!"
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Manual execution"
          elif [ "${{ github.event_name }}" == "schedule" ]; then
            echo "Running on schedule"
          else
            echo "Unknown trigger: ${{ github.event_name }}"
          fi
