name: JSON Input

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Provide JSON config (e.g. {"runTests": true, "env": "dev"})'
        required: true
        default: '{"runTests": true, "env": "dev"}'

jobs:
  parse-config:
    runs-on: ubuntu-latest
    steps:
      - name: Extract and display configuration
        run: |
          echo "Run Tests: $RUN_TESTS"
          echo "Environment: $ENVIRONMENT"
        env:
          RUN_TESTS: ${{ fromJson(inputs.config).runTests }}
          ENVIRONMENT: ${{ fromJson(inputs.config).env }}
